export const localAlbums = [
    {
        id: 'nada-personal',
        title: 'Nada Personal (Remastered)',
        artist: 'Soda Stereo',
        year: 1985,
        cover: 'assets/covers-img/popular-albums/nada-personal.webp',
        totalTracks: 10,
        releaseDate: '1985-11-15',
        tracks: [
            { id: "track 1", title: "Nada Personal", duration: "4:57", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Nada Personal (Remasterizado 2007).mp3' },
            { id: "track 2", title: "Si No Fuera Por...", duration: "3:29", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Si No Fuera Por... (Remasterizado 2007).mp3' },
            { id: "track 3", title: "Cuando Pase El Temblor", duration: "3:48", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Cuando Pase El Temblor (Remasterizado 2007).mp3' },
            { id: "track 4", title: "Danza Rota", duration: "3:35", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Danza Rota (Remasterizado 2007).mp3' },
            { id: "track 5", title: "El Cuerpo Del Delito", duration: "3:50", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/El Cuerpo Del Delito (Remasterizado 2007).mp3' },
            { id: "track 6", title: "Juego De Seducción", duration: "3:21", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Juegos De Seducción (Remasterizado 2007).mp3' },
            { id: "track 7", title: "Estoy Azulado", duration: "5:21", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Estoy Azulado (Remasterizado 2007).mp3' },
            { id: "track 8", title: "Observándonos (Satélites)", duration: "3:09", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Observándonos (Satélites) (Remasterizado 2007).mp3' },
            { id: "track 9", title: "Imágenes Retro", duration: "3:55", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Imágenes Retro (Remasterizado 2007).mp3' },
            { id: "track 10", title: "Ecos", duration: "4:58", audioFile: 'assets/audio/albums/Nada Personal (Remastered)/Ecos (Remasterizado 2007).mp3' }
        ]
    },
    {
        id: 'violator',
        title: 'Violator (Deluxe)',
        artist: 'Depeche Mode',
        year: 1990,
        cover: 'assets/covers-img/popular-albums/Depeche-Mode-Violator.webp',
        totalTracks: 9,
        releaseDate: '1990-03-19',
        genre: 'Electronic, Synth-pop',
        tracks: [
            { id: "track 1", title: "World In My Eyes", duration: "4:27", audioFile: 'assets/audio/albums/Depeche Mode - Violator/01 - World In My Eyes.mp3' },
            { id: "track 2", title: "Sweetest Perfection", duration: "4:42", audioFile: 'assets/audio/albums/Depeche Mode - Violator/02 - Sweetest Perfection.mp3' },
            { id: "track 3", title: "Personal Jesus", duration: "4:19", audioFile: 'assets/audio/albums/Depeche Mode - Violator/03 - Personal Jesus.mp3' },
            { id: "track 4", title: "Halo", duration: "4:28", audioFile: 'assets/audio/albums/Depeche Mode - Violator/04 - Halo.mp3' },
            { id: "track 5", title: "Waiting For The Night", duration: "6:07", audioFile: 'assets/audio/albums/Depeche Mode - Violator/05 - Waiting for the Night.mp3' },
            { id: "track 6", title: "Enjoy The Silence", duration: "6:13", audioFile: 'assets/audio/albums/Depeche Mode - Violator/06 - Enjoy the Silence.mp3' },
            { id: "track 7", title: "Policy Of Truth", duration: "4:54", audioFile: 'assets/audio/albums/Depeche Mode - Violator/07 - Policy of Truth.mp3' },
            { id: "track 8", title: "Blue Dress", duration: "5:38", audioFile: 'assets/audio/albums/Depeche Mode - Violator/08 - Blue Dress.mp3' },
            { id: "track 9", title: "Clean", duration: "5:33", audioFile: 'assets/audio/albums/Depeche Mode - Violator/09 - Clean.mp3' },
            { id: "track 10", title: "Dangerous", duration: "4:22", audioFile: 'assets/audio/albums/Depeche Mode - Violator/10 - Dangerous.mp3' },
            { id: "track 11", title: "Memphisto", duration: "4:08", audioFile: 'assets/audio/albums/Depeche Mode - Violator/11 - Memphisto.mp3' },
            { id: "track 12", title: "Silbeling", duration: "3:17", audioFile: 'assets/audio/albums/Depeche Mode - Violator/12 - Sibeling.mp3' },
            { id: "track 13", title: "Kaleid (7 Version)", duration: "4:17", audioFile: 'assets/audio/albums/Depeche Mode - Violator/13 - Kaleid (7" Version).mp3' },
            { id: "track 14", title: "Happiest Girl (Jack Mix)", duration: "4:57", audioFile: 'assets/audio/albums/Depeche Mode - Violator/14 - Happiest Girl (Jack Mix).mp3' },
            { id: "track 15", title: "Sea Of Sins (Tonal Mix)", duration: "4:44", audioFile: 'assets/audio/albums/Depeche Mode - Violator/15 - Sea of Sin(Tonal Mix).mp3' }
        ]
    },
    {
        id: 'killers',
        title: 'Killers (2015 Remaster)',
        artist: 'Iron Maiden',
        year: 1981,
        cover: 'assets/covers-img/popular-albums/Iron-Maiden-–-Killers-ghostcultmag.webp',
        totalTracks: 10,
        releaseDate: '1981-02-02',
        genre: 'Heavy Metal',
        tracks: [
            { id: "track 1", title: "The Ides Of March", duration: "1:48", audioFile: 'assets/audio/albums/Killers/01 The Ides Of March.mp3' },
            { id: "track 2", title: "Wrathchild", duration: "2:54", audioFile: 'assets/audio/albums/Killers/02 Wrathchild.mp3' },
            { id: "track 3", title: "Murders In The Rue Morgue", duration: "4:14", audioFile: 'assets/audio/albums/Killers/03 Murders In The Rue Morgue.mp3' },
            { id: "track 4", title: "Another Life", duration: "3:22", audioFile: 'assets/audio/albums/Killers/04 Another Life.mp3' },
            { id: "track 5", title: "Genghis Khan", duration: "3:02", audioFile: 'assets/audio/albums/Killers/05 Genghis Khan.mp3' },
            { id: "track 6", title: "Innocent Exile", duration: "3:50", audioFile: 'assets/audio/albums/Killers/06 Innocent Exile.mp3' },
            { id: "track 7", title: "Killers", duration: "4:58", audioFile: 'assets/audio/albums/Killers/07 Killers.mp3' },
            { id: "track 8", title: "Prodigal Son", duration: "6:05", audioFile: 'assets/audio/albums/Killers/08 Prodigal Son.mp3' },
            { id: "track 9", title: "Purgatory", duration: "3:18", audioFile: 'assets/audio/albums/Killers/09 Purgatory.mp3' },
            { id: "track 10", title: "Drifter", duration: "4:47", audioFile: 'assets/audio/albums/Killers/11 Drifter.mp3' }
        ]
    },
    {
        id: 'starboy',
        title: 'Starboy',
        artist: 'The Weeknd',
        explicit: true,
        year: 2016,
        cover: 'assets/covers-img/popular-albums/starboy.webp',
        totalTracks: 18,
        releaseDate: '2016-11-25',
        genre: 'R&B, Pop',
        tracks: [
            { id: "track 1", title: "Starboy (feat. Daft Punk)", duration: "3:50", audioFile: 'assets/audio/albums/The Weeknd - Starboy/01 - Starboy.mp3' },
            { id: "track 2", title: "Party Monster", duration: "4:09", audioFile: 'assets/audio/albums/The Weeknd - Starboy/02 - Party Monster.mp3' },
            { id: "track 3", title: "False Alarm", duration: "3:40", audioFile: 'assets/audio/albums/The Weeknd - Starboy/03 - False Alarm.mp3' },
            { id: "track 4", title: "Reminder", duration: "3:38", audioFile: 'assets/audio/albums/The Weeknd - Starboy/04 - Reminder.mp3' },
            { id: "track 5", title: "Rockin'", duration: "3:52", audioFile: "assets/audio/albums/The Weeknd - Starboy/05 - Rockin'.mp3" },
            { id: "track 6", title: "Secrets", duration: "4:25", audioFile: 'assets/audio/albums/The Weeknd - Starboy/06 - Secrets.mp3' },
            { id: "track 7", title: "True Colors", duration: "3:26", audioFile: 'assets/audio/albums/The Weeknd - Starboy/07 - True Colors.mp3' },
            { id: "track 8", title: "Stargirl Interlude (feat. Lana Del Rey)", duration: "1:51", audioFile: 'assets/audio/albums/The Weeknd - Starboy/08 - Stargirl Interlude.mp3' },
            { id: "track 9", title: "Sidewalks (feat. Kendrick Lamar)", duration: "3:51", audioFile: 'assets/audio/albums/The Weeknd - Starboy/09 - Sidewalks.mp3' },
            { id: "track 10", title: "Six Feet Under", duration: "3:57", audioFile: 'assets/audio/albums/The Weeknd - Starboy/10 - Six Feet Under.mp3' },
            { id: "track 11", title: "Love To Lay", duration: "3:43", audioFile: 'assets/audio/albums/The Weeknd - Starboy/11 - Love To Lay.mp3' },
            { id: "track 12", title: "A Lonely Night", duration: "3:40", audioFile: 'assets/audio/albums/The Weeknd - Starboy/12 - A Lonely Night.mp3' },
            { id: "track 13", title: "Attention", duration: "3:17", audioFile: 'assets/audio/albums/The Weeknd - Starboy/13 - Attention.mp3' },
            { id: "track 14", title: "Ordinary Life", duration: "3:41", audioFile: 'assets/audio/albums/The Weeknd - Starboy/14 - Ordinary Life.mp3' },
            { id: "track 15", title: "Nothing Without You", duration: "3:18", audioFile: 'assets/audio/albums/The Weeknd - Starboy/15 - Nothing Without You.mp3' },
            { id: "track 16", title: "All I Know (feat. Future)", duration: "5:21", audioFile: 'assets/audio/albums/The Weeknd - Starboy/16 - All I Know.mp3' },
            { id: "track 17", title: "Die For You", duration: "4:20", audioFile: 'assets/audio/albums/The Weeknd - Starboy/17 - Die For You.mp3' },
            { id: "track 18", title: "I Feel It Coming (feat. Daft Punk)", duration: "4:29", audioFile: 'assets/audio/albums/The Weeknd - Starboy/18 - I Feel It Coming.mp3' }
        ]
    },
    {
        id: 'seventeen-seconds',
        title: 'Seventeen Seconds',
        artist: 'The Cure',
        year: 1980,
        cover: 'assets/covers-img/popular-albums/The Cure- Seventeen Seconds.webp',
        totalTracks: 10,
        releaseDate: '1980-04-18',
        genre: 'Post-Punk, Gothic Rock',
        tracks: [
            { id: "track 1", title: "A Reflection", duration: "1:52", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/01 - A Reflection.mp3' },
            { id: "track 2", title: "Play for Today", duration: "3:39", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/02 - Play For Today.mp3' },
            { id: "track 3", title: "Secrets", duration: "3:28", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/03 - Secrets.mp3' },
            { id: "track 4", title: "In Your House", duration: "5:26", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/04 - In Your House.mp3' },
            { id: "track 5", title: "Three", duration: "2:36", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/05 - Three.mp3' },
            { id: "track 6", title: "The Final Sound", duration: "0:53", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/06 - The Final Sound.mp3' },
            { id: "track 7", title: "A Forest", duration: "4:53", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/07 - A Forest.mp3' },
            { id: "track 8", title: "M", duration: "3:03", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/08 - M.mp3' },
            { id: "track 9", title: "At Night", duration: "5:54", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/09 - At Night.mp3' },
            { id: "track 10", title: "Seventeen Seconds", duration: "4:00", audioFile: 'assets/audio/albums/Seventeen Seconds (2005 Reissue)/10 - Seventeen Seconds.mp3' }
        ]
    }
];